### ISSUE TITLE
worker errors

### ISSUE THREAD

**Issue by fumunda** [ciur/papermerge#13]
The search function returns nothing.  Even when searching for a word in a file name. Any help?

Also, when starting the worker, logs shows it as fine.  But when I upload a file to be OCR'd, i get this....   For every file. Eventually i can highlight words in documents but i cannot search for anything using those words.  Just empty search results.

`Arguments: ()
[2020-05-02 14:25:44,325: INFO/ForkPoolWorker-1] worker_log success task_id=3e55acf4-883e-4ec0-bd3f-1d70cc3c4e2b user_id=1 doc_id=91 page_num=1 page_type=pdf total_exec_time=9.04
[2020-05-02 14:25:44,331: INFO/ForkPoolWorker-1] Task pmworker.tasks.ocr_page[3e55acf4-883e-4ec0-bd3f-1d70cc3c4e2b] succeeded in 9.049290722003207s: True
[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] --- Logging error ---

[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] Traceback (most recent call last):

[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] File "/usr/lib/python3.7/logging/handlers.py", line 934, in emit

self.socket.send(msg)
[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] OSError: [Errno 9] Bad file descriptor

[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] During handling of the above exception, another exception occurred:

[2020-05-02 14:25:44,333: WARNING/ForkPoolWorker-1] Traceback (most recent call last):

[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] File "/usr/lib/python3.7/logging/handlers.py", line 855, in _connect_unixsocket

self.socket.connect(address)
[2020-05-02 14:25:44,334: INFO/MainProcess] Received task: pmworker.tasks.ocr_page[13d1bd01-8fef-4510-9dc9-bab1738e1f5a]
[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] FileNotFoundError: [Errno 2] No such file or directory

[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] During handling of the above exception, another exception occurred:

[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] Traceback (most recent call last):

[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] File "/usr/lib/python3.7/logging/handlers.py", line 937, in emit

self._connect_unixsocket(self.address)
[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] File "/usr/lib/python3.7/logging/handlers.py", line 866, in _connect_unixsocket

self.socket.connect(address)
[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] FileNotFoundError: [Errno 2] No such file or directory

[2020-05-02 14:25:44,334: WARNING/ForkPoolWorker-1] Call stack:

[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/bin/celery", line 8, in <module>

sys.exit(main())
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/__main__.py", line 16, in main

_main()
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/celery.py", line 322, in main

cmd.execute_from_commandline(argv)
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/celery.py", line 495, in execute_from_commandline

super(CeleryCommand, self).execute_from_commandline(argv)))
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/base.py", line 305, in execute_from_commandline

return self.handle_argv(self.prog_name, argv[1:])
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/celery.py", line 487, in handle_argv

return self.execute(command, argv)
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/celery.py", line 419, in execute

).run_from_argv(self.prog_name, argv[1:], command=argv[0])
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/worker.py", line 223, in run_from_argv

return self(*args, **options)
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/base.py", line 253, in __call__

ret = self.run(*args, **kwargs)
[2020-05-02 14:25:44,335: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bin/worker.py", line 259, in run

worker.start()
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/worker/worker.py", line 205, in start

self.blueprint.start(self)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bootsteps.py", line 119, in start

step.start(parent)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/bootsteps.py", line 369, in start

return self.obj.start()
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/base.py", line 132, in start

self.on_start()
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/prefork.py", line 117, in on_start

**self.options)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 1046, in __init__

self._create_worker_process(i)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 1158, in _create_worker_process

w.start()
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/process.py", line 124, in start

self._popen = self._Popen(self)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/context.py", line 333, in _Popen

return Popen(process_obj)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/popen_fork.py", line 24, in __init__

self._launch(process_obj)
[2020-05-02 14:25:44,336: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/popen_fork.py", line 79, in _launch

code = process_obj._bootstrap()
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/process.py", line 327, in _bootstrap

self.run()
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/process.py", line 114, in run

self._target(*self._args, **self._kwargs)
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 292, in __call__

sys.exit(self.workloop(pid=pid))
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 362, in workloop

result = (True, prepare_result(fun(*args, **kwargs)))
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 558, in _fast_trace_task

uuid, args, kwargs, request,
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 385, in trace_task

R = retval = fun(*args, **kwargs)
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/usr/local/lib/python3.7/dist-packages/celery/app/trace.py", line 650, in __protected_call__

return self.run(*args, **kwargs)
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] File "/opt/papermerge-worker/pmworker/tasks.py", line 95, in ocr_page

f"worker_log task_id={self.request.id}"
[2020-05-02 14:25:44,337: WARNING/ForkPoolWorker-1] Message: 'worker_log task_id=ac060393-e3fa-4a6f-9ea4-16809a0b56f5 user_id=1 doc_id=93 page_num=1'

Arguments: ()
[2020-05-02 14:25:44,333: INFO/ForkPoolWorker-1] worker_log task_id=ac060393-e3fa-4a6f-9ea4-16809a0b56f5 user_id=1 doc_id=93 page_num=1`

**Comment by ciur** [comment]
I assume you ran papermerge inside docker container.
There are two separate issues here. 

First I forgot to include in docker image cron jobs for so called indexer. Without them it is not possible to find OCRed documents.
Second, i think there is a issue with logging.yml file of the worker.

Anyway, I fixed both problems and pushed latest docker images to [docker hub](https://hub.docker.com/repository/docker/eugenci/papermerge). Latest stable images are tagged now with "eugenci/papermerge:**1.2.x**" and "eugenci/papermerge:**latest**" docker tags.

Now, you can:

`$ git clone https://github.com/ciur/papermerge papermerge-proj`
`$ cd papermerge-proj/docker`
`$ docker-compose up -d`

And you won't have above mentioned issues.

**Comment by fumunda** [comment]
Yeah sorry about forgetting the docker container part.  Yes i am running it in docker.

I will update and tell you how it goes in a bit. 

Thanks for looking into it right away. 😁

**Comment by fumunda** [comment]
Ok. seems to have worked.  Errors are gone and search now returns results but only on newly uploaded and ocr'd files.  Any way i can make it re do all of them without having to re upload them all?

Thanks again!!

**Comment by fumunda** [comment]
i take that back.  it appears to be working on all of them now!!

thanks again. i will call this closed!
