### ISSUE TITLE
MySQL Connect Issues

### ISSUE THREAD

**Issue by doughnet** [ciur/papermerge#293]
Using Ubuntu 20.04 (LXC VM)

Papermerge works fine with SQLite as the backend database but when changing the configuration to MySQL/MariaDB it doesn't connect. 

**papermerge.conf.py**
DBTYPE = "mysql"
DBUSER = "pm"
DBHOST = "localhost"
DBNAME = "pm"
DBPORT = "3306"
DBPASS = "pm"

**Error when trying to migrate:**

```
Traceback (most recent call last):
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 3306?
received invalid response to SSL negotiation: j


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 83, in wrapped
    res = handle_func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 86, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/migrations/executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 49, in __init__
    self.build_graph()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/migrations/loader.py", line 212, in build_graph
    self.applied_migrations = recorder.applied_migrations()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 76, in applied_migrations
    if self.has_table():
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/migrations/recorder.py", line 56, in has_table
    return self.Migration._meta.db_table in self.connection.introspection.table_names(self.connection.cursor())
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 260, in cursor
    return self._cursor()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 236, in _cursor
    self.ensure_connection()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 220, in ensure_connection
    self.connect()
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/base/base.py", line 197, in connect
    self.connection = self.get_new_connection(conn_params)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/utils/asyncio.py", line 26, in inner
    return func(*args, **kwargs)
  File "/root/papermerge/.venv/lib/python3.8/site-packages/django/db/backends/postgresql/base.py", line 185, in get_new_connection
    connection = Database.connect(**conn_params)
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
django.db.utils.OperationalError: could not connect to server: Connection refused
        Is the server running on host "localhost" (::1) and accepting
        TCP/IP connections on port 3306?
received invalid response to SSL negotiation: j
```

- I've tried running via localhost & an external MySQL database to confirm it wasn't a specific issue with the MySQL installation.
- I've confirmed being able to access both databases/tables with the credentials with mysql client via CLI

Any help would be greatly appreciated!

**Comment by ciur** [comment]
I see in provided error messages that Papermerge thinks it deals with PostgreSQL database. It looks like it ignores ``DBTYPE = "mysql"`` configuration.

Thank you for reporting this issue!

**Comment by doughnet** [comment]
Awesome. Thanks for catching. I didn't notice that part of the error.

**Comment by doughnet** [comment]
I tried with Postgres and it worked fine. Can't wait for the MySQL fix.

**Comment by ciur** [comment]
I cannot reproduce it. 

I tried both v1.5.5 and latest development version. It works in both cases.
Are you using it from within docker container ? Can you please describe the steps you followed to install Papermerge ?

**Comment by ciur** [comment]
However, I received exactly same error, when I switched back postgres i.e. ``DBTYPE="pg'`` BUT by mistake left ``DBPORT="3306"`` i.e. mysql port. Maybe you can check if your sql db port number is correct.

**Comment by firmicus** [comment]
@ciur : request to reopen this .... still an issue: can't connect to mysql/mariadb
