### ISSUE TITLE
TypeError - Using Apache2 With WSGI

### ISSUE THREAD

**Issue by doughnet** [ciur/papermerge#300]
**Getting this error:**

```
Exception ignored in: <function Local.__del__ at 0x7f3372cf05e0>
Traceback (most recent call last):
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f3372cf15e0>
Traceback (most recent call last):
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f3372cf15e0>
Traceback (most recent call last):
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Feb 05 23:44:16.481921 2021] [mpm_prefork:notice] [pid 16533] AH00169: caught SIGTERM, shutting down
[Fri Feb 05 23:44:16.554715 2021] [mpm_prefork:notice] [pid 26151] AH00163: Apache/2.4.41 (Ubuntu) mod_wsgi/4.6.8 Python/3.8 configured -- resuming normal operations
[Fri Feb 05 23:44:16.554768 2021] [core:notice] [pid 26151] AH00094: Command line: '/usr/sbin/apache2'

```
**Papermerge seems to be running fine.  Noticed that it is not importing from directly automatically though.  Manual upload hangs/doesn't work.**

**Ubuntu 20.04 LXC**

**Comment by doughnet** [comment]
Seems permission issue with media folder (not told in the tutorial for installing in production to do this).
