### ISSUE TITLE
Error on altering metadata fields

### ISSUE THREAD

**Issue by noax** [ciur/papermerge#335]
**Description**
After creating a folder with some subfolders and documents in it, I've added some metadata fields on it. The initial propagation worked just fine, but when I try to remove or add some fields now, it constantly fails.

**Expected**
After altering the metadata, changes should be saved and propagated to all child entries (folders and documents)

**Actual**
Adding new metadata fields, removing existing ones (but not all) or even saving without modifications fails with "There was an error while saving metadata." and the following stack trace:
```
papermerge_app | [Sat Mar 06 14:54:09.077000 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164] ERROR:django.request:Internal Server Error: /metadata/node/199
papermerge_app | [Sat Mar 06 14:54:09.077026 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164] Traceback (most recent call last):
papermerge_app | [Sat Mar 06 14:54:09.077031 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
papermerge_app | [Sat Mar 06 14:54:09.077049 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     response = get_response(request)
papermerge_app | [Sat Mar 06 14:54:09.077052 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
papermerge_app | [Sat Mar 06 14:54:09.077055 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
papermerge_app | [Sat Mar 06 14:54:09.077058 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
papermerge_app | [Sat Mar 06 14:54:09.077062 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     return view_func(request, *args, **kwargs)
papermerge_app | [Sat Mar 06 14:54:09.077065 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/views/metadata.py", line 98, in metadata
papermerge_app | [Sat Mar 06 14:54:09.077068 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     item.kv.update(
papermerge_app | [Sat Mar 06 14:54:09.077071 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/kvstore.py", line 545, in update
papermerge_app | [Sat Mar 06 14:54:09.077087 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.apply_updates(
papermerge_app | [Sat Mar 06 14:54:09.077090 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/kvstore.py", line 472, in apply_updates
papermerge_app | [Sat Mar 06 14:54:09.077093 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.propagate(
papermerge_app | [Sat Mar 06 14:54:09.077119 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/kvstore.py", line 583, in propagate
papermerge_app | [Sat Mar 06 14:54:09.077122 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.instance.propagate_changes(
papermerge_app | [Sat Mar 06 14:54:09.077125 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 379, in propagate_changes
papermerge_app | [Sat Mar 06 14:54:09.077128 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     node.apply_diffs(
papermerge_app | [Sat Mar 06 14:54:09.077131 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 351, in apply_diffs
papermerge_app | [Sat Mar 06 14:54:09.077134 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.apply_diff(diff, attr_updates)
papermerge_app | [Sat Mar 06 14:54:09.077137 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 305, in apply_diff
papermerge_app | [Sat Mar 06 14:54:09.077141 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self._apply_diff_update(diff, attr_updates)
papermerge_app | [Sat Mar 06 14:54:09.077144 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 293, in _apply_diff_update
papermerge_app | [Sat Mar 06 14:54:09.077147 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.kv.apply_updates(updates)
papermerge_app | [Sat Mar 06 14:54:09.077150 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/kvstore.py", line 472, in apply_updates
papermerge_app | [Sat Mar 06 14:54:09.077153 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.propagate(
papermerge_app | [Sat Mar 06 14:54:09.077156 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/kvstore.py", line 583, in propagate
papermerge_app | [Sat Mar 06 14:54:09.077159 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.instance.propagate_changes(
papermerge_app | [Sat Mar 06 14:54:09.077162 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 379, in propagate_changes
papermerge_app | [Sat Mar 06 14:54:09.077165 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     node.apply_diffs(
papermerge_app | [Sat Mar 06 14:54:09.077168 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 351, in apply_diffs
papermerge_app | [Sat Mar 06 14:54:09.077174 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self.apply_diff(diff, attr_updates)
papermerge_app | [Sat Mar 06 14:54:09.077216 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 305, in apply_diff
papermerge_app | [Sat Mar 06 14:54:09.077235 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     self._apply_diff_update(diff, attr_updates)
papermerge_app | [Sat Mar 06 14:54:09.077262 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]   File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/models/node.py", line 297, in _apply_diff_update
papermerge_app | [Sat Mar 06 14:54:09.077279 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164]     raise ValueError(
papermerge_app | [Sat Mar 06 14:54:09.077282 2021] [wsgi:error] [pid 1414:tid 140125064894208] [remote 10.100.71.31:45164] ValueError: Don't know how to replace None (found in Diff(update, []))
```
Removing **all** existing metadata fields results in the Interface reporting "Metadata successfully saved." and no errors in the log, but on reload the metadata fields show up unchanged.

**Info:**
 - OS: [Ubuntu 20.04 LTS]
 - Browser [Firefox,Chromium]
-  Database [MariaDB]
 - Papermerge Version [eugenci/papermerge:2.0.0.rc45 (docker)]

**Comment by noax** [comment]
![Peek 2021-03-06 15-58](https://user-images.githubusercontent.com/10982591/110211064-1a377100-7e95-11eb-931c-dc481172ecb2.gif)

**Comment by ciur** [comment]
@noax, thanks for detailed report! I will have a look a come back with more info.
