### ISSUE TITLE
Installation on Ubuntu 20.04 fails

### ISSUE THREAD

**Issue by rolikeusch** [ciur/papermerge#344]
I'm not able to install papermerge on fresh Ubuntu 20.04 Server, i see always the following error when i invoke manage.py and have no idea how i can fix this:

`(.venv) me@papermerge:/opt/papermerge$ ./manage.py migrate
Traceback (most recent call last):
  File "./manage.py", line 24, in <module>
    execute_from_command_line(sys.argv)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 330, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 371, in execute
    output = self.handle(*args, **options)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 85, in wrapped
    res = handle_func(*args, **kwargs)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/commands/migrate.py", line 75, in handle
    self.check(databases=[database])
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/management/base.py", line 392, in check
    all_issues = checks.run_checks(
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/django/core/checks/registry.py", line 70, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/opt/papermerge/.venv/lib/python3.8/site-packages/papermerge/core/checks.py", line 110, in binaries_check
    binary = os.path.basename(binary_path)
  File "/usr/lib/python3.8/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType`

I followed the Installation guide found [here](https://papermerge.readthedocs.io/en/latest/setup/manual_way.html#detailed-version). Any Ideas what is missing here?

**Info:**
 - Distributor ID:	Ubuntu
    Description:	Ubuntu 20.04.2 LTS
    Release:	20.04
    Codename:	focal
 - Papermerge Version v2.0.0rc48

**Comment by ciur** [comment]
Thanks for quick heads up!

It is a nasty bug. Here is workaround:

1.First install dependencies:
```
$ pip3 install -r requirements/base.txt
```
2. Check installation path of ``stapler`` utility with 
```
$ which stapler
```
3. Add that path (absolute path to stapler utility) to papermerge.conf.py:
```
BINARY_STAPLER = "/home/eugen/Lab/DMS/.venv/bin/stapler"
```

**Comment by ciur** [comment]
I added default value for stapler.
If you will get latest source code (via ``git pull`` command), it should work without workaround.

**Comment by rolikeusch** [comment]
This was it! With the new Version it works!
Thanks for the fast support.
