### ISSUE TITLE
Can't add metadata at specific root-folder: "There was an error while saving metadata"

### ISSUE THREAD

**Issue by Popoboxxo** [ciur/papermerge#372]
**Description**

When setting a meta date at root level, papermerge reports an error  "There was an error while saving metadata."

![2021-04-29 18_57_12-Window](https://user-images.githubusercontent.com/11631395/116592390-3cdb8880-a920-11eb-8e77-42f945fa3892.png)

Error:

![2021-04-29 19_01_22-Window](https://user-images.githubusercontent.com/11631395/116592416-44029680-a920-11eb-9d55-43fcfa167ce9.png)

Logfile:

Logfile

[2021-04-29 19:06:30,041: DEBUG/Beat] beat: Waking up in 29.99 seconds.
_**Internal Server Error: /metadata/node/83**_
Traceback (most recent call last):
File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 47, in inner
response = get_response(request)
File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 181, in _get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/usr/local/lib/python3.8/dist-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
return view_func(request, *args, **kwargs)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/views/metadata.py", line 98, in metadata
item.kv.update(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/kvstore.py", line 545, in update
self.apply_updates(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/kvstore.py", line 472, in apply_updates
self.propagate(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/kvstore.py", line 583, in propagate
self.instance.propagate_changes(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 379, in propagate_changes
node.apply_diffs(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 351, in apply_diffs
self.apply_diff(diff, attr_updates)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 305, in apply_diff
self._apply_diff_update(diff, attr_updates)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 293, in _apply_diff_update
self.kv.apply_updates(updates)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/kvstore.py", line 472, in apply_updates
self.propagate(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/kvstore.py", line 583, in propagate
self.instance.propagate_changes(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 379, in propagate_changes
node.apply_diffs(
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 351, in apply_diffs
self.apply_diff(diff, attr_updates)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 305, in apply_diff
self._apply_diff_update(diff, attr_updates)
File "/usr/local/lib/python3.8/dist-packages/papermerge/core/models/node.py", line 297, in _apply_diff_update
raise ValueError(
ValueError: Don't know how to replace None (found in Diff(update, []))
[pid: 554|app: 0|req: 3160/3212] 172.20.100.11 () {60 vars in 1344 bytes} [Thu Apr 29 19:06:38 2021] PUT /metadata/node/83 => generated 156057 bytes in 255 msecs (HTTP/1.1 500) 7 headers in 226 bytes (2 switches on core 0)

**Actual**

Meta-Date "Datum" could not be stored. No metadata type can be configured.

![2021-04-29 19_07_52-Window](https://user-images.githubusercontent.com/11631395/116592232-10c00780-a920-11eb-834c-b5a8c2e8dc39.png)

But on another node the setting works without any problems.

![2021-04-29 19_09_03-Window](https://user-images.githubusercontent.com/11631395/116592255-17e71580-a920-11eb-816b-6355c621c85b.png)

**Info:**
- OS: Windows 10
 - Browser: Microsoft Edge Version 90.0.818.49 (Offizielles Build) (64-Bit)
-  Database Maria DB 5.5.57
 - Papermerge Version 2.0 -> linuxserver/papermerge:v2.0.1-ls35

**Comment by ciur** [comment]
You probably wanted to add a common metadata field for all documents and folders - a case which I never considered, but it actually make perfect sense.
@Popoboxxo, thanks for opening this issue!

**Comment by Popoboxxo** [comment]
Ah, ok.

of cause, that would be a nice Feature! But in my case I actually tried  only to set the/a metadata on a main folder.

(the "faulty"/error-throwing-Folder im core_basetreenode) 
([2021-04-30 23:09:07,917: DEBUG/Beat] beat: Waking up in 22.43 seconds.
Internal Server Error: /metadata/node/83)
![image](https://user-images.githubusercontent.com/11631395/116755857-5c031480-aa0b-11eb-812c-70aa07535ba5.png)

New added Folders/ other, also with documents inside, works smoothly wich new metadata.
