### ISSUE TITLE
automatic file import stopped working

### ISSUE THREAD

**Issue by Sepphod** [ciur/papermerge#393]
I have a docker setup. I don't need a mail import so far. I just want import my documents via files. So I did my test runs. The first two documents worked like almost like a charm. The first document was added twice. Anyway an adding of any new file to the importer directory doesn't trigger anything. But when I execute the import manually be _./manage.py local_importer_ it works fine. Any idea how can I get the automatic import back?
thnx

**Comment by devnio** [comment]
For me it also doesn't work. I configured the IMPORT_DIR inside the papermerge.conf.py file and restarted the docker. However when I place documents inside the specified IMPORT_DIR nothing happens. How can I debug this?

I'm kind of new to papermerge and I'm in the process of setting up my system, it has been 2 weeks and I'm slowly getting there. Thanks for this beautiful open source project.

**Comment by Sepphod** [comment]
I have some infos. Seems that the worker got an issue during the OCR of one file - see log below, Than it stopped working. So the still not OCRed files are still in the importer dir. Until I don't delete them manually the importer won't work automatically. After deletion of those files - it works again. But the crashes happens quite often. This brings me to my next question. I have an extra OCR pipeline with tesseract and imagemagick. So I don't need the OCR feature and it seems not quite stable. So is it possible to deactivate the OCR feature?
here  the log of the papermerge_worker
[2021-07-08 06:39:07,712: ERROR/ForkPoolWorker-2] Task papermerge.core.management.commands.worker.import_from_local_folder[c8436101-f970-4efb-a992-25b9879bb8d7] raised unexpected: Exception('Error occured while getting document page count.')
Traceback (most recent call last):
  File "/opt/app/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 405, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/app/.venv/lib/python3.8/site-packages/celery/app/trace.py", line 697, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/management/commands/worker.py", line 70, in import_from_local_folder
    import_documents(settings.PAPERMERGE_IMPORTER_DIR)
  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/importers/local.py", line 52, in import_documents
    doc = go_through_pipelines(init_kwargs, apply_kwargs)
  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/import_pipeline.py", line 371, in go_through_pipelines
    doc = importer.apply(**apply_kwargs)
  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/import_pipeline.py", line 272, in apply
    page_count = self.page_count()
  File "/opt/app/.venv/lib/python3.8/site-packages/papermerge/core/import_pipeline.py", line 156, in page_count
    return get_pagecount(self.path)
  File "/opt/app/.venv/lib/python3.8/site-packages/mglib/pdfinfo.py", line 126, in get_pagecount
    raise Exception("Error occured while getting document page count.")
Exception: Error occured while getting document page count.
