### ISSUE TITLE
Error while uploading file

### ISSUE THREAD

**Issue by sachinpathare** [ciur/papermerge#41]
Internal Server Error: /upload/
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\contrib\auth\decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\views\generic\base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "C:\Users\Admin\papermerge-proj\papermerge\core\views\documents.py", line 282, in post
    page_count = get_pagecount(f.temporary_file_path())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\site-packages\mglib\pdfinfo.py", line 83, in get_pagecount
    compl = subprocess.run(
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python38-32\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
[21/Jul/2020 17:46:30] "POST /upload/ HTTP/1.1" 500 128740

**Comment by ciur** [comment]
I think you did not install [poppler utils](https://papermerge.readthedocs.io/en/latest/requirements.html#requirements).
Can you double check that please ?
If you type in command line:

  ```
  $ pdfinfo -v 
```
You should see something like:

```
pdfinfo version 0.62.0
Copyright 2005-2017 The Poppler Developers - http://poppler.freedesktop.org
Copyright 1996-2011 Glyph & Cog, LLC
```

**Comment by sachinpathare** [comment]
@ciur i have install package still same error.

**Comment by ciur** [comment]
ah, man, wait a second. You are using Windows machine, right?
I never tested on Windows!
Here in [requiremens](https://papermerge.readthedocs.io/en/latest/requirements.html#requirements) I mentioned that you need a Unix-flavoured machine (some linux distro or mac os).
Sorry, man, it is not designed to work on Windows :)
Maybe you can try via Docker image ? I never tried to run docker+windows but in theory should work.
