### ISSUE TITLE
Papermerge-CLI Uploading Error

### ISSUE THREAD

**Issue by drtechnofreak** [ciur/papermerge#538]
papermerge-cli import Uploaded/
Importing Uploaded/23435-9-041.pdf
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 62, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/backoff/_sync.py", line 105, in retry
ret = target(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/rest.py", line 150, in upload_document
documents_api_instance.upload_file(
File "/usr/local/lib/python3.10/dist-packages/papermerge_restapi_client/paths/api_documents_document_id_upload_file_name/put.py", line 257, in upload_file
return self._upload_file_oapg(
File "/usr/local/lib/python3.10/dist-packages/papermerge_restapi_client/paths/api_documents_document_id_upload_file_name/put.py", line 235, in _upload_file_oapg
raise exceptions.ApiException(api_response=api_response)
papermerge_restapi_client.exceptions.ApiException: (413)
Reason: Request Entity Too Large
HTTP response headers: HTTPHeaderDict({'Server': 'nginx/1.18.0', 'Date': 'Sat, 18 Mar 2023 21:05:57 GMT', 'Content-Type': 'text/html', 'Content-Length': '183', 'Connection': 'close'})
HTTP response body: b'<html>\r\n<head><title>413 Request Entity Too Large</title></head>\r\n<body>\r\n<center><h1>413 Request Entity Too Large</h1></center>\r\n<hr><center>nginx/1.18.0</center>\r\n</body>\r\n</html>\r\n'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 62, in inner
return func(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/rest.py", line 326, in perform_import
upload_document(
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 72, in inner
raise ApiException from e
papermerge_restapi_client.exceptions.ApiException: (None)
Reason: None
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/local/bin/papermerge-cli", line 8, in <module>
sys.exit(cli())
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1130, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1055, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1657, in invoke
return _process_result(sub_ctx.command.invoke(sub_ctx))
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 760, in invoke
return __callback(*args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/click/decorators.py", line 26, in new_func
return f(get_current_context(), *args, **kwargs)
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/main.py", line 107, in _import
perform_import(
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 39, in inner
return func(**kwargs)
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 54, in inner
return func(**kwargs)
File "/usr/local/lib/python3.10/dist-packages/papermerge_cli/utils.py", line 72, in inner
raise ApiException from e
papermerge_restapi_client.exceptions.ApiException: (None)
Reason: None

**Comment by ptitboogy** [comment]
Hello,
I've got the same issue with file as small as 2,2 MB.
How are we supposed to bulk import big documents ?

Thansk

**Comment by ciur** [comment]
My guess is that the issue may be with the configurations in this file:

https://github.com/papermerge/docker/blob/master/papermerge/nginx.conf

(according to this article: https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/)

**Comment by ptitboogy** [comment]
Hi Eugen,

I made the change directly in the running docker image and I confirm that it's working as expected.
Can you please make this change directly in the next image that you will build ?

Many thanks for your support.

**Comment by drtechnofreak** [comment]
Hi Guys,

I'm struggling to find the nginx config file within the docker.. 

Can someone give me the container & path I should be looking for?

Cheers

**Comment by ptitboogy** [comment]
The file to modify within the container is /etc/nginx/nginx.conf
You can add this parameter in the "server" section

**Comment by drtechnofreak** [comment]
Hi, When I try to CD to etc. I get "permission denied: unknown"

I can only get to bin/app  I have checked & I am under root with docker exec

**Comment by ptitboogy** [comment]
![image](https://user-images.githubusercontent.com/23520678/229064964-ab9d43c3-f9d9-4768-a263-def1750c9a1e.png)
![image](https://user-images.githubusercontent.com/23520678/229065076-be3ee367-0067-418f-8f4a-d8141a47a7dc.png)

**Comment by drtechnofreak** [comment]
![DMS](https://user-images.githubusercontent.com/128376380/229066204-f63b9291-c887-4834-bbd0-deb4f72262d5.png)
 Thankyou so much.. I'll test to see if it works now :)

**Comment by drtechnofreak** [comment]
Well it fixed the web upload, but the papermerge-cli is still reporting the same error.

I don't want to upload using web as it's a long process with the amount of files I have.

Hopefully fixed in the next pull :0

**Comment by ciur** [comment]
I released [2.1.9](https://github.com/papermerge/papermerge-core/releases) which contains above mentioned fix. The max size for uploaded document (max size one document can have) is [hardcoded to 100 MB](https://github.com/papermerge/docker/blob/master/papermerge/nginx.conf#L15).

Please close this ticket in case you think the issue was resolved.

**Comment by drtechnofreak** [comment]
![image](https://user-images.githubusercontent.com/128376380/229497512-7fdc458c-6e3d-4555-b8dc-06ca8ae2cd9e.png)
Lovely stuff chaps..  

I'll see how far PaperMerge can go with around 400gb of PDF's :)
